version: "3.3"
services:
  base:
    image: experiencebase
    build:
      context: .
  catalogue:
    image: wellcome/catalogue_webapp:${CONTAINER_TAG:-test}
    build:
      context: ./catalogue
    depends_on:
      - base
    ports:
      - "3000:3000"
  content:
    image: wellcome/content_webapp:${CONTAINER_TAG:-test}
    build:
      context: ./content
    depends_on:
      - base
    ports:
      - "3000:3000"
