version: "3.3"
services:
  common:
    build:
      context: .
      dockerfile: common/Dockerfile
  catalogue:
    image: wellcome/catalogue_webapp:${CONTAINER_TAG:-test}
    build:
      context: .
      dockerfile: catalogue/Dockerfile
  content:
    image: wellcome/content_webapp:${CONTAINER_TAG:-test}
    build:
      context: .
      dockerfile: content/Dockerfile
  cardigan:
    build:
      context: .
      dockerfile: cardigan/Dockerfile
    volumes:
      - "./cardigan:/dist"
  pa11y:
    build:
      context: ./pa11y
    volumes:
      - "./pa11y:/dist"
  dash:
    build:
      context: ./dash
    volumes:
      - "./dash:/dist"
  toggles:
    build:
      context: ./toggles
    volumes:
      - "./toggles/.dist:/dist"
  edge_lambdas:
    build:
      context: ./cache/edge_lambdas
    volumes:
      - "./cache/edge_lambdas:/dist"
