version: "3.3"
services:
  common:
    build:
      context: .
      dockerfile: common/Dockerfile
  catalogue:
    image: uk.ac.wellcome/catalogue_webapp:${CONTAINER_TAG:-test}
    build:
      context: .
      dockerfile: catalogue/Dockerfile
  content:
    image: uk.ac.wellcome/content_webapp:${CONTAINER_TAG:-test}
    build:
      context: .
      dockerfile: content/Dockerfile
  cardigan:
    build:
      context: .
      dockerfile: cardigan/Dockerfile
    volumes:
      - "./cardigan:/dist"
  dash:
    build:
      context: ./dash
    volumes:
      - "./dash:/dist"
  edge_lambdas:
    build:
      context: ./cache/edge_lambdas
  toggles:
    build:
      context: ./toggles
  pa11y:
    build:
      context: ./pa11y
