steps:
  - label: "e2e test:desktop [prod]"
    plugins:
      - docker-compose#v3.5.0:
          run: e2e
          env:
            - PLAYWRIGHT_BASE_URL=https://wellcomecollection.org
          command: ["yarn", "test"]

  - label: "e2e test:mobile [prod]"
    plugins:
      - docker-compose#v3.5.0:
          run: e2e
          env:
            - PLAYWRIGHT_BASE_URL=https://wellcomecollection.org
          command: ["yarn", "test:mobile"]
