- label: ":docker: Build"
  plugins:
    - seek-oss/aws-sm#v2.1.0:
        env:
          DOCKER_HUB_PASSWORD: builds/docker_hub_password
    - ecr#v2.1.1:
        login: true
    - docker-compose#v3.5.0:
        build:
          - common
          - catalogue
          - content
          - edge_lambdas
        image-repository: 760097843905.dkr.ecr.eu-west-1.amazonaws.com/uk.ac.wellcome/buildkite

- wait

- label: "test common"
  plugins:
    - ecr#v2.1.1:
        login: true
    - docker-compose#v3.5.0:
        run: common
        command: ["yarn", "test"]
        workdir: /usr/src/app/webapp/common

- label: "test catalogue"
  plugins:
    - ecr#v2.1.1:
        login: true
    - docker-compose#v3.5.0:
        run: catalogue
        command: ["yarn", "test"]

- label: "test content"
  plugins:
    - ecr#v2.1.1:
        login: true
    - docker-compose#v3.5.0:
        run: content
        command: ["yarn", "test"]

- label: "test edge_lambdas"
  plugins:
    - ecr#v2.1.1:
        login: true
    - docker-compose#v3.5.0:
        run: edge_lambdas
        command: ["yarn", "test"]

- wait

- label: "deploy catalogue (ecr image)"
  plugins:
    - ecr#v2.1.1:
        login: true
    - ecr#v2.1.1:
        login: true
    - docker-compose#v3.5.0:
        push:
          - catalogue:760097843905.dkr.ecr.eu-west-1.amazonaws.com/uk.ac.wellcome/catalogue_webapp:${BUILDKITE_COMMIT}
          - catalogue:760097843905.dkr.ecr.eu-west-1.amazonaws.com/uk.ac.wellcome/catalogue_webapp:latest

- label: "deploy catalogue (bundle analysis)"
  plugins:
    - ecr#v2.1.1:
        login: true
    - docker-compose#v3.5.0:
        run: catalogue
        command: [ "yarn", "deploy_bundle_analysis" ]

- label: "deploy content (ecr image)"
  plugins:
    - ecr#v2.1.1:
        login: true
    - docker-compose#v3.5.0:
        push:
          - content:760097843905.dkr.ecr.eu-west-1.amazonaws.com/uk.ac.wellcome/content_webapp:${BUILDKITE_COMMIT}
          - content:760097843905.dkr.ecr.eu-west-1.amazonaws.com/uk.ac.wellcome/content_webapp:latest

- label: "deploy content (bundle analysis)"
  plugins:
    - ecr#v2.1.1:
        login: true
    - docker-compose#v3.5.0:
        run: content
        command: [ "yarn", "deploy_bundle_analysis" ]

- label: "deploy dash"
  plugins:
    - ecr#v2.1.1:
        login: true
    - docker-compose#v3.5.0:
        run: dash
        command: [ "yarn", "deploy" ]

- label: "deploy cardigan"
  plugins:
    - ecr#v2.1.1:
        login: true
    - docker-compose#v3.5.0:
        run: cardigan
        command: [ "yarn", "deploy" ]

- label: "deploy dash"
  plugins:
    - ecr#v2.1.1:
        login: true
    - docker-compose#v3.5.0:
        run: dash
        command: [ "yarn", "deploy" ]

- label: "deploy toggles"
  plugins:
    - ecr#v2.1.1:
        login: true
    - docker-compose#v3.5.0:
        run: toggles
        command: [ "yarn", "deploy" ]

- label: "deploy pa11y"
  plugins:
    - ecr#v2.1.1:
        login: true
    - docker-compose#v3.5.0:
        run: pa11y
        command: [ "yarn", "deploy" ]

- label: "deploy edge_lambdas"
  plugins:
    - ecr#v2.1.1:
        login: true
    - docker-compose#v3.5.0:
        run: edge_lambdas
        command: [ "yarn", "deploy" ]
