steps:
  - label: "release to stage"
    command: echo "$BUILDKITE_COMMIT $BUILDKITE_BUILD_URL"
    concurrency: 1
    concurrency_group: "experience-deploy"
  
  - wait

  - label: "e2e test:desktop [stage]"
    command: echo "testing stage"

  - wait

  - block: ":rocket: Release to prod"
    branches: "master"
    prompt: "Have you checked staging?"
    blocked_state: "running"

  - label: "Deplyments steps"
    trigger: "experience-deploy-prod"

notify:
  - slack:
      channels:
        - "#wc-experience"
      message: "Deploying [bloop] to staging..."