- label: ":docker: Build"
  plugins:
    - seek-oss/aws-sm#v2.1.0:
        env:
          DOCKER_HUB_PASSWORD: builds/docker_hub_password
    - docker-login#v2.0.1:
        username: wellcometravis
        password-env: DOCKER_HUB_PASSWORD
    - docker-compose#v3.5.0:
        build:
          - common
          - catalogue
          - content
        image-repository: index.docker.io/wellcome/myrepo

- wait

- label: "test common"
  plugins:
    - docker-compose#v3.5.0:
        run: common
        command: ["yarn", "test"]
        workdir: /usr/src/app/webapp/common

- label: "test catalogue"
  plugins:
    - docker-compose#v3.5.0:
        run: catalogue
        command: ["yarn", "test"]

- label: "test content"
  plugins:
    - docker-compose#v3.5.0:
        run: content
        command: ["yarn", "test"]

- label: "test edge_lambdas"
  plugins:
    - docker-compose#v3.5.0:
        run: edge_lambdas
        command: ["yarn", "test"]

- wait

- label: "deploy toggles"
  plugins:
    - docker-compose#v3.5.0:
        run: toggles
        command: [ "yarn", "deploy" ]

- label: "deploy pa11y"
  plugins:
    - docker-compose#v3.5.0:
        run: pa11y
        command: [ "yarn", "deploy" ]

- label: "deploy edge_lambdas"
  plugins:
    - docker-compose#v3.5.0:
        run: edge_lambdas
        command: [ "yarn", "deploy" ]

- label: "deploy catalogue"
  plugins:
    - ecr#v2.1.1:
        login: true
    - docker-compose#v3.5.0:
        push:
          - catalogue:760097843905.dkr.ecr.eu-west-1.amazonaws.com/uk.ac.wellcome/catalogue_webapp:${BUILDKITE_COMMIT}

- label: "deploy content"
  plugins:
    - ecr#v2.1.1:
        login: true
    - docker-compose#v3.5.0:
        push:
          - content:760097843905.dkr.ecr.eu-west-1.amazonaws.com/uk.ac.wellcome/content_webapp:${BUILDKITE_COMMIT}

- label: "deploy cardigan"
  artifact_paths: "cardigan/.dist/*"
  plugins:
    - docker-compose#v3.5.0:
        run: cardigan

- label: "deploy dash"
  artifact_paths: "dash/.dist/*"
  plugins:
    - docker-compose#v3.5.0:
        run: dash
