steps:
  - label: "deploy to stage"
    concurrency: 1
    concurrency_group: "experience-deploy"
    plugins:
      - docker#v3.5.0:
          image: 760097843905.dkr.ecr.eu-west-1.amazonaws.com/wellcome/weco-deploy:5.6.16
          workdir: /repo
          mount-ssh-agent: true
          command: [
              "--confirm",
              "--project-id", "experience",
              "release-deploy",
              "--from-label", "ref.$BUILDKITE_COMMIT",
              "--environment-id", "stage",
              "--description", $BUILDKITE_BUILD_URL,
              "--confirmation-wait-for", 3540] # Session times out at 3600s / 1 hour

  - wait

  - label: "e2e test:desktop [stage]"
    plugins:
      - docker-compose#v3.5.0:
          run: e2e
          env:
            - PLAYWRIGHT_BASE_URL=https://www-stage.wellcomecollection.org
          command: ["yarn", "test"]

  - label: "e2e test:mobile [stage]"
    plugins:
      - docker-compose#v3.5.0:
          run: e2e
          env:
            - PLAYWRIGHT_BASE_URL=https://www-stage.wellcomecollection.org
          command: ["yarn", "test:mobile"]

  - wait

  - block: ":rocket: deploy to prod"
    prompt: "Have you checked staging?"

  - label: "deploy to prod"
    trigger: "experience-deploy-prod"
    build:
      message: "${BUILDKITE_MESSAGE}"
      commit: "${BUILDKITE_COMMIT}"
      branch: "${BUILDKITE_BRANCH}"
      env:
        BUILDKITE_PULL_REQUEST: "${BUILDKITE_PULL_REQUEST}"
        BUILDKITE_PULL_REQUEST_BASE_BRANCH: "${BUILDKITE_PULL_REQUEST_BASE_BRANCH}"
        BUILDKITE_PULL_REQUEST_REPO: "${BUILDKITE_PULL_REQUEST_REPO}"
