- label: ":docker: Build"
  agents:
    queue: docker-builder
  plugins:
    - seek-oss/aws-sm#v2.1.0:
        env:
          DOCKER_HUB_PASSWORD: builds/docker_hub_password
    - docker-login#v2.0.1:
        username: wellcometravis
        password-env: DOCKER_HUB_PASSWORD
    - docker-compose#v3.5.0:
        build:
          - base
          - catalogue
          - content
        image-repository: index.docker.io/wellcome/buildkite
#- wait
#- label: "test common"
#  plugins:
#    - docker-compose#v3.5.0:
#        run: base
#        command: ["yarn", "test"]
#        workdir: /usr/src/app/webapp/common
#- label: "test flow"
#  plugins:
#    - docker-compose#v3.5.0:
#        run: catalogue
#        command: ["yarn", "flow"]
#        workdir: /usr/src/app/webapp
#- label: "test catalogue"
#  plugins:
#    - docker-compose#v3.5.0:
#        run: catalogue
#        command: ["yarn", "test"]
#- label: "test content"
#  plugins:
#    - docker-compose#v3.5.0:
#        run: content
#        command: ["yarn", "test"]
