- label: ":docker: Build"
  plugins:
    - wellcomecollection/aws-assume-role#v0.2.2:
        role: "arn:aws:iam::130871440101:role/experience-ci"
    - ecr#v2.1.1:
        login: true
    - docker-compose#v3.5.0:
        build-parallel: true
        build:
          - common
          - catalogue
          - content
          - edge_lambdas
        image-repository: 130871440101.dkr.ecr.eu-west-1.amazonaws.com/uk.ac.wellcome/buildkite

- wait

- label: "test common"
  plugins:
    - wellcomecollection/aws-assume-role#v0.2.2:
        role: "arn:aws:iam::130871440101:role/experience-ci"
    - ecr#v2.1.1:
        login: true
    - docker-compose#v3.5.0:
        run: common
        command: ["yarn", "test"]

- label: "test catalogue"
  plugins:
    - wellcomecollection/aws-assume-role#v0.2.2:
        role: "arn:aws:iam::130871440101:role/experience-ci"
    - ecr#v2.1.1:
        login: true
    - docker-compose#v3.5.0:
        run: catalogue
        command: ["yarn", "test"]

- label: "test content"
  plugins:
    - wellcomecollection/aws-assume-role#v0.2.2:
        role: "arn:aws:iam::130871440101:role/experience-ci"
    - ecr#v2.1.1:
        login: true
    - docker-compose#v3.5.0:
        run: content
        command: ["yarn", "test"]

- label: "test edge_lambdas"
  plugins:
    - wellcomecollection/aws-assume-role#v0.2.2:
        role: "arn:aws:iam::130871440101:role/experience-ci"
    - ecr#v2.1.1:
        login: true
    - docker-compose#v3.5.0:
        run: edge_lambdas
        command: ["yarn", "test"]

- wait

- label: "deploy catalogue (ecr image)"
  if: build.branch == "master"
  plugins:
    - wellcomecollection/aws-assume-role#v0.2.2:
        role: "arn:aws:iam::130871440101:role/experience-ci"
    - ecr#v2.1.1:
        login: true
    - docker-compose#v3.5.0:
        push:
          - catalogue:130871440101.dkr.ecr.eu-west-1.amazonaws.com/uk.ac.wellcome/catalogue_webapp:ref.${BUILDKITE_COMMIT}
          - catalogue:130871440101.dkr.ecr.eu-west-1.amazonaws.com/uk.ac.wellcome/catalogue_webapp:latest

- label: "deploy catalogue (bundle analysis)"
  if: build.branch == "master"
  plugins:
    - wellcomecollection/aws-assume-role#v0.2.2:
        role: "arn:aws:iam::130871440101:role/experience-ci"
    - ecr#v2.1.1:
        login: true
    - docker-compose#v3.5.0:
        run: catalogue
        command: [ "yarn", "deployBundleAnalysis" ]
        env:
          - AWS_ACCESS_KEY_ID
          - AWS_SECRET_ACCESS_KEY
          - AWS_SESSION_TOKEN

- label: "deploy content (ecr image)"
  if: build.branch == "master"
  plugins:
    - wellcomecollection/aws-assume-role#v0.2.2:
        role: "arn:aws:iam::130871440101:role/experience-ci"
    - ecr#v2.1.1:
        login: true
    - docker-compose#v3.5.0:
        push:
          - content:130871440101.dkr.ecr.eu-west-1.amazonaws.com/uk.ac.wellcome/content_webapp:ref.${BUILDKITE_COMMIT}
          - content:130871440101.dkr.ecr.eu-west-1.amazonaws.com/uk.ac.wellcome/content_webapp:latest

- label: "deploy content (bundle analysis)"
  if: build.branch == "master"
  plugins:
    - wellcomecollection/aws-assume-role#v0.2.2:
        role: "arn:aws:iam::130871440101:role/experience-ci"
    - ecr#v2.1.1:
        login: true
    - docker-compose#v3.5.0:
        run: content
        command: [ "yarn", "deployBundleAnalysis" ]
        env:
          - AWS_ACCESS_KEY_ID
          - AWS_SECRET_ACCESS_KEY
          - AWS_SESSION_TOKEN

- label: "deploy dash"
  if: build.branch == "master"
  plugins:
    - wellcomecollection/aws-assume-role#v0.2.2:
        role: "arn:aws:iam::130871440101:role/experience-ci"
    - ecr#v2.1.1:
        login: true
    - docker-compose#v3.5.0:
        run: dash
        command: [ "yarn", "deploy" ]
        env:
          - AWS_ACCESS_KEY_ID
          - AWS_SECRET_ACCESS_KEY
          - AWS_SESSION_TOKEN

- label: "deploy cardigan"
  if: build.branch == "master"
  plugins:
    - wellcomecollection/aws-assume-role#v0.2.2:
        role: "arn:aws:iam::130871440101:role/experience-ci"
    - ecr#v2.1.1:
        login: true
    - docker-compose#v3.5.0:
        run: cardigan
        command: [ "yarn", "deploy" ]
        env:
          - AWS_ACCESS_KEY_ID
          - AWS_SECRET_ACCESS_KEY
          - AWS_SESSION_TOKEN

- label: "deploy dash"
  if: build.branch == "master"
  plugins:
    - wellcomecollection/aws-assume-role#v0.2.2:
        role: "arn:aws:iam::130871440101:role/experience-ci"
    - ecr#v2.1.1:
        login: true
    - docker-compose#v3.5.0:
        run: dash
        command: [ "yarn", "deploy" ]
        env:
          - AWS_ACCESS_KEY_ID
          - AWS_SECRET_ACCESS_KEY
          - AWS_SESSION_TOKEN

- label: "deploy toggles"
  if: build.branch == "master"
  plugins:
    - wellcomecollection/aws-assume-role#v0.2.2:
        role: "arn:aws:iam::130871440101:role/experience-ci"
    - ecr#v2.1.1:
        login: true
    - docker-compose#v3.5.0:
        run: toggles
        command: [ "yarn", "deploy" ]
        env:
          - AWS_ACCESS_KEY_ID
          - AWS_SECRET_ACCESS_KEY
          - AWS_SESSION_TOKEN

- label: "deploy pa11y"
  if: build.branch == "master"
  plugins:
    - wellcomecollection/aws-assume-role#v0.2.2:
        role: "arn:aws:iam::130871440101:role/experience-ci"
    - ecr#v2.1.1:
        login: true
    - docker-compose#v3.5.0:
        run: pa11y
        command: [ "yarn", "deploy" ]
        env:
          - AWS_ACCESS_KEY_ID
          - AWS_SECRET_ACCESS_KEY
          - AWS_SESSION_TOKEN

- label: "deploy edge_lambdas"
  if: build.branch == "master"
  plugins:
    - wellcomecollection/aws-assume-role#v0.2.2:
        role: "arn:aws:iam::130871440101:role/experience-ci"
    - ecr#v2.1.1:
        login: true
    - docker-compose#v3.5.0:
        run: edge_lambdas
        command: [ "yarn", "deploy" ]
        env:
          - AWS_ACCESS_KEY_ID
          - AWS_SECRET_ACCESS_KEY
          - AWS_SESSION_TOKEN

- label: "deploy updown"
  if: build.branch == "master"
  plugins:
    - wellcomecollection/aws-assume-role#v0.2.2:
        role: "arn:aws:iam::130871440101:role/experience-ci"
    - ecr#v2.1.1:
        login: true
    - docker-compose#v3.5.0:
        run: updown
        command: [ "yarn", "checks" ]
        env:
          - AWS_ACCESS_KEY_ID
          - AWS_SECRET_ACCESS_KEY
          - AWS_SESSION_TOKEN

- wait

- label: "release to stage"
  if: build.branch == "master"
  plugins:
    - docker#v3.5.0:
        image: wellcome/weco-deploy:5.6.11
        workdir: /repo
        mount-ssh-agent: true
        command: [
            "--confirm",
            "release-deploy",
            "--from-label", "ref.$BUILDKITE_COMMIT",
            "--environment-id", "stage",
            "--description", $BUILDKITE_BUILD_URL,
            "--confirmation-wait-for", 3540] # Session times out at 3600s / 1 hour

- wait

- label: "e2e test: desktop"
  if: build.branch == "master"
  plugins:
    - docker-compose#v3.5.0:
        run: e2e
        env:
          - PLAYWRIGHT_BASE_URL=https://www-stage.wellcomecollection.org
        command: ["yarn", "test"]

- label: "e2e test: mobile"
  if: build.branch == "master"
  plugins:
    - docker-compose#v3.5.0:
        run: e2e
        env:
          - PLAYWRIGHT_BASE_URL=https://www-stage.wellcomecollection.org
        command: ["yarn", "test:mobile"]  

- wait

- label: "Integration pipeline"
  trigger: "integration"
  async: true

- wait

- block:
    branches: "master feat/ci_prod_deploy"
    prompt: ":rocket: Release to prod, have you checked [staging]?"

- label: "release to prod"
  branches: "master feat/ci_prod_deploy"
  plugins:
    - docker#v3.5.0:
        image: wellcome/weco-deploy:5.6.11
        workdir: /repo
        mount-ssh-agent: true
        command: [
            "--confirm",
            "release-deploy",
            "--from-label", "ref.$BUILDKITE_COMMIT",
            "--environment-id", "stage",
            "--description", $BUILDKITE_BUILD_URL,
            "--confirmation-wait-for", 3540] # Session times out at 3600s / 1 hour
