- label: ":docker: Build"
  plugins:
    - seek-oss/aws-sm#v2.1.0:
        env:
          DOCKER_HUB_PASSWORD: builds/docker_hub_password
    - docker-login#v2.0.1:
        username: wellcometravis
        password-env: DOCKER_HUB_PASSWORD
    - docker-compose#v3.5.0:
        build:
          - common
          - catalogue
          - content
          - cardigan
        image-repository: index.docker.io/wellcome/buildkite

- wait

- label: "cardigan artifacts"
  artifact_paths: "cardigan/.dist"
  plugins:
    - docker-compose#v3.5.0:
        run: cardigan

- label: "test common"
  plugins:
    - docker-compose#v3.5.0:
        run: common
        command: ["yarn", "test"]
        workdir: /usr/src/app/webapp/common

- label: "test catalogue"
  plugins:
    - docker-compose#v3.5.0:
        run: catalogue
        command: ["yarn", "test"]

- label: "test content"
  plugins:
    - docker-compose#v3.5.0:
        run: content
        command: ["yarn", "test"]
