steps:
  - label: "release to stage"
    command: echo "$BUILDKITE_COMMIT $BUILDKITE_BUILD_URL"
    concurrency: 1
    concurrency_group: "experience-deploy"
  
  - wait

  - label: "e2e test:desktop [stage]"
    command: echo "testing stage"

  - wait

  - block: ":rocket: Release to prod"
    prompt: "Have you checked staging?"
    blocked_state: "running"

  - label: "Deplyments steps"
    trigger: "experience-deploy-prod"
    build:
      message: "${BUILDKITE_MESSAGE}"
      commit: "${BUILDKITE_COMMIT}"
      branch: "${BUILDKITE_BRANCH}"
      env:
        BUILDKITE_PULL_REQUEST: "${BUILDKITE_PULL_REQUEST}"
        BUILDKITE_PULL_REQUEST_BASE_BRANCH: "${BUILDKITE_PULL_REQUEST_BASE_BRANCH}"
        BUILDKITE_PULL_REQUEST_REPO: "${BUILDKITE_PULL_REQUEST_REPO}"

notify:
  - slack:
      channels:
        - "#wc-experience"
      message: "Deploying [bloop] to staging..."