- label: test flow
  plugins:
    - docker#v3.5.0:
        image: "node:12.18.3"
        always-pull: true
  command:
    - yarn testFlow
- label: test common
  plugins:
    - docker#v3.5.0:
        image: "node:12.18.3"
        always-pull: true
  command:
    - yarn testCommon
- wait
- label: test catalogue
  plugins:
    - docker#v3.5.0:
        image: "node:12.18.3"
        always-pull: true
  command:
    - yarn testCatalogue
- label: test content
  plugins:
    - docker#v3.5.0:
        image: "node:12.18.3"
        always-pull: true
  command:
    - yarn testContent
